import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased font-inter `}
      >

        <div className="  mx-auto min-h-screen over dark:bg-white">
          {children}
        </div>
      </body>
    </html>
  );
}
