import type { Metadata } from "next";
import "./globals.css";
import Nav from './components/Nav';
import Footer from './components/Footer';


export const metadata: Metadata = {
  title: "Jasamarga Bali Tol",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased font-inter `}
      >

        <Nav></Nav>
        <div className="  mx-auto min-h-screen over dark:bg-white">


          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
